[package]
publish = false
name = "demo"
version = "0.36.0"
edition = "2018"

[dependencies]
anyhow = "1.0.42"
env_logger = "0.9.0"
log = "0.4.14"
rillrate = { version = "0.36.0", path = "../rillrate" }
